version: '3.8'
services:
  web_app:
    build: 
      context: ./
      dockerfile: Dockerfile.web_app
    image: web_app:v1
    container_name: fastapi_webapp
    volumes: 
      - /home/mitera/rss_backup/210705_news/data:/usr/src/web_app/data
      # - C:/Users/sri.sai.praveen.gadi/Downloads/scraping_output/210705_news/data:/usr/src/web_app/data
    ports:
      - 8080:8080
    expose:
      - 8080