version: '3.8'

networks:
  backend:
  public_frontend:
    external: true

services:
        
  mda:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: ["uvicorn", "app:app", "--root-path", "/mda", "--host", "0.0.0.0", "--port", "8080"]
    image: mda-webapp:latest
    restart: unless-stopped
    volumes: 
      - /mnt/data/xxx-osint/rss_backup/210705_news:/usr/src/web_app/data
    networks:
      - public_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mda.rule=PathPrefix(`/mda`)"
      - "traefik.http.routers.mda.middlewares=strip-mda@docker"
      - "traefik.http.middlewares.strip-mda.stripprefix.prefixes=/mda"